"""initial enterprise cms schema

Revision ID: fc7a58cf045c
Revises: 
Create Date: 2026-07-16 16:51:40.313570
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fc7a58cf045c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'platform_admin', 'auditor', 'support', 'developer', 'user', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_locale', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_sites_key'), 'sites', ['key'], unique=True)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=30), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=True)
    op.create_index(op.f('ix_api_keys_site_id'), 'api_keys', ['site_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_site_id'), 'audit_logs', ['site_id'], unique=False)
    op.create_index('ix_audit_site_time', 'audit_logs', ['site_id', 'created_at'], unique=False)
    op.create_table('content_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_definition', sa.JSON(), nullable=False),
    sa.Column('display_field', sa.String(length=80), nullable=False),
    sa.Column('is_singleton', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'key', name='uq_site_content_type')
    )
    op.create_index(op.f('ix_content_types_key'), 'content_types', ['key'], unique=False)
    op.create_index(op.f('ix_content_types_site_id'), 'content_types', ['site_id'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'key', name='uq_site_environment')
    )
    op.create_index(op.f('ix_environments_key'), 'environments', ['key'], unique=False)
    op.create_index(op.f('ix_environments_site_id'), 'environments', ['site_id'], unique=False)
    op.create_table('locales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'code', name='uq_site_locale')
    )
    op.create_index(op.f('ix_locales_code'), 'locales', ['code'], unique=False)
    op.create_index(op.f('ix_locales_site_id'), 'locales', ['site_id'], unique=False)
    op.create_table('media_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['media_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'parent_id', 'name', name='uq_media_folder')
    )
    op.create_index(op.f('ix_media_folders_site_id'), 'media_folders', ['site_id'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'key', name='uq_site_menu')
    )
    op.create_index(op.f('ix_menus_key'), 'menus', ['key'], unique=False)
    op.create_index(op.f('ix_menus_site_id'), 'menus', ['site_id'], unique=False)
    op.create_table('redirects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('destination_url', sa.String(length=1000), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'source_path', name='uq_site_redirect')
    )
    op.create_index(op.f('ix_redirects_site_id'), 'redirects', ['site_id'], unique=False)
    op.create_index(op.f('ix_redirects_source_path'), 'redirects', ['source_path'], unique=False)
    op.create_table('site_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'site_admin', 'content_manager', 'editor', 'author', 'reviewer', 'seo_manager', 'media_manager', 'developer', 'viewer', name='siterole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'user_id', name='uq_site_member')
    )
    op.create_index(op.f('ix_site_members_role'), 'site_members', ['role'], unique=False)
    op.create_index(op.f('ix_site_members_site_id'), 'site_members', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_members_user_id'), 'site_members', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'slug', name='uq_site_tag')
    )
    op.create_index(op.f('ix_tags_site_id'), 'tags', ['site_id'], unique=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('secret', sa.String(length=160), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_site_id'), 'webhook_endpoints', ['site_id'], unique=False)
    op.create_table('content_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('content_type_id', sa.String(length=36), nullable=False),
    sa.Column('locale', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'approved', 'published', 'scheduled', 'rejected', 'archived', name='entrystatus'), nullable=False),
    sa.Column('workflow_stage', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('seo', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('published_by', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'content_type_id', 'locale', 'slug', name='uq_entry_slug_scope')
    )
    op.create_index(op.f('ix_content_entries_content_type_id'), 'content_entries', ['content_type_id'], unique=False)
    op.create_index(op.f('ix_content_entries_environment_id'), 'content_entries', ['environment_id'], unique=False)
    op.create_index(op.f('ix_content_entries_locale'), 'content_entries', ['locale'], unique=False)
    op.create_index(op.f('ix_content_entries_published_at'), 'content_entries', ['published_at'], unique=False)
    op.create_index(op.f('ix_content_entries_scheduled_for'), 'content_entries', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_content_entries_site_id'), 'content_entries', ['site_id'], unique=False)
    op.create_index(op.f('ix_content_entries_slug'), 'content_entries', ['slug'], unique=False)
    op.create_index(op.f('ix_content_entries_status'), 'content_entries', ['status'], unique=False)
    op.create_index(op.f('ix_content_entries_title'), 'content_entries', ['title'], unique=False)
    op.create_index('ix_entries_site_status_updated', 'content_entries', ['site_id', 'status', 'updated_at'], unique=False)
    op.create_index('ix_entries_type_locale_status', 'content_entries', ['content_type_id', 'locale', 'status'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=800), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'ready', 'quarantined', 'archived', name='mediastatus'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['media_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_media_assets_checksum_sha256'), 'media_assets', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_media_assets_folder_id'), 'media_assets', ['folder_id'], unique=False)
    op.create_index(op.f('ix_media_assets_mime_type'), 'media_assets', ['mime_type'], unique=False)
    op.create_index(op.f('ix_media_assets_site_id'), 'media_assets', ['site_id'], unique=False)
    op.create_index(op.f('ix_media_assets_status'), 'media_assets', ['status'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('webhook_id', sa.String(length=36), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='webhookdeliverystatus'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_event_name'), 'webhook_deliveries', ['event_name'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('content_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['content_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'version', name='uq_entry_revision')
    )
    op.create_index(op.f('ix_content_revisions_created_at'), 'content_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_revisions_entry_id'), 'content_revisions', ['entry_id'], unique=False)
    op.create_table('entry_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['content_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['entry_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_comments_entry_id'), 'entry_comments', ['entry_id'], unique=False)
    op.create_index(op.f('ix_entry_comments_is_resolved'), 'entry_comments', ['is_resolved'], unique=False)
    op.create_table('entry_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['content_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'tag_id', name='uq_entry_tag')
    )
    op.create_index(op.f('ix_entry_tags_entry_id'), 'entry_tags', ['entry_id'], unique=False)
    op.create_index(op.f('ix_entry_tags_tag_id'), 'entry_tags', ['tag_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('menu_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=True),
    sa.Column('entry_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('open_in_new_tab', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['content_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_menu_id'), 'menu_items', ['menu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_menu_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_entry_tags_tag_id'), table_name='entry_tags')
    op.drop_index(op.f('ix_entry_tags_entry_id'), table_name='entry_tags')
    op.drop_table('entry_tags')
    op.drop_index(op.f('ix_entry_comments_is_resolved'), table_name='entry_comments')
    op.drop_index(op.f('ix_entry_comments_entry_id'), table_name='entry_comments')
    op.drop_table('entry_comments')
    op.drop_index(op.f('ix_content_revisions_entry_id'), table_name='content_revisions')
    op.drop_index(op.f('ix_content_revisions_created_at'), table_name='content_revisions')
    op.drop_table('content_revisions')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_name'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_media_assets_status'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_site_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_mime_type'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_folder_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_checksum_sha256'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_entries_type_locale_status', table_name='content_entries')
    op.drop_index('ix_entries_site_status_updated', table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_title'), table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_status'), table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_slug'), table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_site_id'), table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_scheduled_for'), table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_published_at'), table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_locale'), table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_environment_id'), table_name='content_entries')
    op.drop_index(op.f('ix_content_entries_content_type_id'), table_name='content_entries')
    op.drop_table('content_entries')
    op.drop_index(op.f('ix_webhook_endpoints_site_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_site_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_site_members_user_id'), table_name='site_members')
    op.drop_index(op.f('ix_site_members_site_id'), table_name='site_members')
    op.drop_index(op.f('ix_site_members_role'), table_name='site_members')
    op.drop_table('site_members')
    op.drop_index(op.f('ix_redirects_source_path'), table_name='redirects')
    op.drop_index(op.f('ix_redirects_site_id'), table_name='redirects')
    op.drop_table('redirects')
    op.drop_index(op.f('ix_menus_site_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_key'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_media_folders_site_id'), table_name='media_folders')
    op.drop_table('media_folders')
    op.drop_index(op.f('ix_locales_site_id'), table_name='locales')
    op.drop_index(op.f('ix_locales_code'), table_name='locales')
    op.drop_table('locales')
    op.drop_index(op.f('ix_environments_site_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_key'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_content_types_site_id'), table_name='content_types')
    op.drop_index(op.f('ix_content_types_key'), table_name='content_types')
    op.drop_table('content_types')
    op.drop_index('ix_audit_site_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_site_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_site_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_key'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
